derps:
  curiosity_derp_win.gif:
    name: 'Curiosity Derp (Windows)'
    credit: 'Leo Natan'
    hideFromPicker: true
  curiosity_derp.gif:
    name: 'Curiosity Derp'
    credit: 'Leo Natan'
    hideFromPicker: true
  derp_angel.png:
    name: 'Derp Angel'
    credit: 'Leo Natan'
  derp_authentic.png:
    name: 'Authentic Graphics Derp'
    credit: 'Leo Natan'
  derp_autoheal.gif:
    name: 'Autoheal Derp'
    credit: 'chiv'
  derp_awesome_in_a_button.gif:
    name: 'Awesome Derp in a Button'
    credit: 'Leo Natan'
  derp_big_boobs.png:
    name: 'My Eyes are up Here'
    credit: 'Leo Natan'
  derp_book_cover.png:
    name: "Don't Judge a Derp by its Cover"
    credit: 'Leo Natan'
  derp_broken_v0.1.png:
    name: 'Broken Derp (0.1)'
    credit: 'Leo Natan'
  derp_broken.png:
    name: 'Broken Derp'
    credit: 'Leo Natan'
  derp_carpet.gif:
    name: 'Derp Carpet (Murder Derp Kill)'
    credit: 'Leo Natan'
    isImage: true
  derp_chucktesta.gif:
    name: 'Derp? Nope Chuck Testa'
    credit: 'Leo Natan'
  derp_console_cash.png:
    name: 'Console Derp Cash'
    credit: 'Leo Natan'
  derp_console_cash_v2.png:
    name: 'Console Derp Cash (v2)'
    credit: 'Leo Natan'
  derp_console_couch.png:
    name: 'Console Couch Derp'
    credit: 'Leo Natan'
  derp_console_cover.png:
    name: 'Cover Shooter Derp'
    credit: 'Leo Natan'
  derp_console_stealth.gif:
    name: 'Stealth Derp'
    credit: 'Leo Natan'
  derp_console.png:
    name: 'Console Derp (Xbox 360)'
    credit: 'Leo Natan'
  derp_cover_shooter.jpg:
    name: 'Cover Shooter Derp'
    credit: 'Unknown'
  derp_customization_micro.gif:
    name: 'Microtransactions Derp'
    credit: 'Leo Natan'
  derp_customization.gif:
    name: 'Customization Derp'
    credit: 'Leo Natan'
  derp_cyberpunk.png:
    name: 'Cyberpunk Derp'
    credit: 'Leo Natan'
  derp_dialup.png:
    name: 'USA Dialup Derp'
    credit: 'Leo Natan'
  derp_diversity.png:
    name: 'Diversity Derp'
    credit: 'Leo Natan'
  derp_drool.png:
    name: 'Drool Derp'
    credit: 'Leo Natan'
  derp_duke_weapons.png:
    name: 'Duke Derpem Weapons'
    credit: 'Leo Natan'
  derp_duke.png:
    name: 'Duke Derpem'
    credit: 'Leo Natan'
  derp_euro.png:
    name: 'Eurovision Derp (Deelix)'
    credit: 'Leo Natan'
  derp_eyeless.png:
    name: 'Eyeless Derp'
    credit: 'Leo Natan'
  derp_follow.png:
    name: 'Follow Derp'
    credit: 'Leo Natan'
  derp_glow.png:
    name: 'Glow Derp'
    credit: 'Leo Natan'
  derp_grammar_nazi.png:
    name: 'Grammar Nazi Derp'
    credit: 'PumpAction'
  derp_hd_achievement_planet.png:
    name: 'Achievement Unlocked (Planet)'
    credit: 'Leo Natan'
  derp_hd_achievement.png:
    name: 'Achievement Unlocked Derp'
    credit: 'Leo Natan'
  derp_HD_durrrr.png:
    name: 'HD Durr'
    credit: 'Leo Natan'
  derp_HD_miracle_port.png:
    name: '“““HD””” Miracle Port'
    credit: 'Leo Natan'
  derp_HD_steroids.png:
    name: 'HD Steroids Derp'
    credit: 'Leo Natan'
  derp_HD.png:
    name: 'HD Derp'
    credit: 'Leo Natan'
  derp_japcrap.png:
    name: 'Japcrap Derp'
    credit: 'Leo Natan'
  derp_jezus.gif:
    name: 'Derp Jesus'
    credit: 'Leo Natan'
    isImage: true
  derp_kinect_arab.gif:
    name: 'Arab Kinect Derp'
    credit: 'Leo Natan'
  derp_kinect_tactical.gif:
    name: 'Tacticool Kinect Derp'
    credit: 'Leo Natan'
  derp_laptop_gamer.png:
    name: 'Laptop “““Gamer””” Derp'
    credit: 'Leo Natan'
  derp_LAW.gif:
    name: 'Horrorderp is teh Law'
    credit: 'Leo Natan'
  derp_lip_fillers.png:
    name: 'Derp Lip Fillers'
    credit: 'LeoNatan'
  derp_manhattan.png:
    name: 'Manhattan Derp'
    credit: 'Leo Natan'
  derp_metacritic.png:
    name: 'Derpacritic'
    credit: 'Interinactive'
  derp_move_cash.gif:
    name: 'PS Move Cash Derp'
    credit: 'Leo Natan'
  derp_nextgen_v2.gif:
    name: 'Next Gen Derp (v2)'
    credit: 'Leo Natan'
  derp_nextgen.gif:
    name: 'Next Gen Derp'
    credit: 'Leo Natan'
  derp_noir.gif:
    name: 'Derp Noir'
    credit: 'Leo Natan'
  derp_pew.gif:
    name: 'Pew Pew Pew Derp'
    credit: 'chiv'
  derp_piercing.png:
    name: 'Piercing Derp'
    credit: 'Leo Natan'
  derp_pink.png:
    name: 'Pink Derp'
    credit: 'Leo Natan'
  derp_post.gif:
    name: 'Derp Post'
    credit: 'Leo Natan'
  derp_prey.gif:
    name: 'Derp Prey'
    credit: 'Leo Natan'
  derp_religion.png:
    name: 'Religion Derp'
    credit: 'Leo Natan'
  derp_roflmao.gif:
    name: 'Derp ROTFLMAO'
    credit: 'Leo Natan'
  derp_roll.png:
    name: 'Half Derp'
    credit: 'Leo Natan'
  derp_rpg.png:
    name: 'Arr Pee Gee Derp'
    credit: 'Leo Natan'
  derp_sin317_lolrofl_picnic.gif:
    name: 'sin317 Mature v3.1 LOLROFL Picnic Derp'
    credit: 'Leo Natan'
  derp_smooth.gif:
    name: 'Smooth 60 Derps per Second'
    credit: 'Leo Natan'
    isImage: true
  derp_sparta.gif:
    name: 'This is NFOHUMP!'
    credit: 'Leo Natan'
    hideFromPicker: true
  derp_stallman_tell_me_more.png:
    name: 'Please, Tell Me More'
    credit: 'Leo Natan'
    isImage: true
  derp_stallman.png:
    name: 'Derp Stallman'
    credit: 'Leo Natan'
    isImage: true
  derp_thief.png:
    name: 'Derp Thi4f'
    credit: 'Leo Natan'
    isImage: true
  derp_to_the_derpth.png:
    name: 'Derp to the Derpth Degree'
    credit: 'Interinactive'
  derp_tracing.png:
    name: 'Derp Tracing'
    credit: 'Leo Natan'
  derp_usa_fat.png:
    name: 'Fat USA Derp'
    credit: 'Leo Natan'
  derp_usa.png:
    name: 'USA Derp'
    credit: 'Leo Natan'
  derp_vietnam_sense_mafia3.gif:
    name: 'Mafia III Vietnam Sense Derp'
    credit: 'Leo Natan'
  derp_vision.png:
    name: "It's Part of my Derp Vision"
    credit: 'Leo Natan'
  derp_woo.gif:
    name: 'Derp Woo'
    credit: 'Leo Natan'
  derp_woo.gif:
    name: 'Derp Woo'
    credit: 'Leo Natan'
  derp-sc2.gif:
    name: 'StarDerp 2'
    credit: 'Leo Natan'
    hideFromPicker: true
  derp-sistine_chapel.png:
    name: 'Sistine Chapel Derp'
    credit: 'Leo Natan'
    isImage: true
  derp-upside.png:
    name: 'Upside Derp'
    credit: 'Leo Natan'
  derp.png:
    name: ':derp:'
    credit: 'inz'
    hideFromPicker: true
  derpalien.png:
    name: 'Derp Alien'
    credit: 'Leo Natan'
  derpared.gif:
    name: 'Derpared Sense'
    credit: 'Leo Natan'
  derpatic_abberation.png:
    name: 'Derpatic Abberation'
    credit: 'Leo Natan'
  derpfruit.png:
    name: 'Derpfruit'
    credit: 'Leo Natan'
  derpmax.png:
    name: 'Derpmax'
    credit: 'Leo Natan'
  derpnet.png:
    name: 'Derpnet'
    credit: 'Leo Natan'
  derps_ark.png:
    name: "Derp's Ark"
    credit: 'Leo Natan'
  derpshield_small.png:
    name: 'Sasuje Derpshield (Small)'
    credit: 'Leo Natan'
  derpshield.png:
    name: 'Sasuje Derpshield'
    credit: 'Leo Natan'
    hideFromPicker: true
  derpspacey.png:
    name: 'Derp Spacey'
    credit: 'Leo Natan'
    isImage: true
  exoderp.gif:
    name: 'Exoderp'
    credit: 'Leo Natan'
  horror_derp_kinect.gif:
    name: 'Horror Derp Kinect'
    credit: 'Leo Natan'
    hideFromPicker: true
  horror_derp.png:
    name: 'Horror Derp'
    credit: 'Leo Natan'
  kinect.gif:
    name: 'Kinect Derp'
    credit: 'Leo Natan'
  mechderp.png:
    name: 'Mech Derp'
    credit: 'Leo Natan'
  move-derp-v2.gif:
    name: 'PS Move Derp (v2)'
    credit: 'Leo Natan'
  move-derp.gif:
    name: 'PS Move Derp'
    credit: 'Leo Natan'
  sausje.jpg:
    name: 'Sausje (Derp)'
    credit: 'Leo Natan'
    isImage: true
  pending_derp.gif:
    name: 'Pending Derp'
    credit: 'Unknown'
  remove_derp_glasses_still_derp.gif:
    name: 'Remove Derp Glasses, Still Derp'
    credit: 'Leo Natan'
    hideFromPicker: true
  remove_derp_glasses.gif:
    name: 'Remove Derp Glasses'
    credit: 'Leo Natan'
    hideFromPicker: true
  s5fskj.png:
    name: 'Console vs PC'
    credit: 'Leo Natan'
    hideFromPicker: true
  sausage-derp.png:
    name: 'Sausje (Derp)'
    credit: 'Leo Natan'
    hideFromPicker: true
  sfl9wo.png:
    name: 'Crystal Derp Ballz'
    credit: 'Leo Natan'
    isImage: true
  derp_usa_texas_grandma_derp.png:
    name: 'Texas Grandma USA Derp'
    credit: 'Leo Natan'
  the_d.png:
    name: 'The D[erp]'
    credit: 'Leo Natan'
    hideFromPicker: true
  wallderp.png:
    name: 'Wallderp'
    credit: 'Leo Natan'
  derp_windows.png:
    name: 'Windows Derp 8/10/11'
    credit: 'Leo Natan'
  derp_medal_of_honor.png:
    name: 'Medal of Honor Derp'
    credit: 'Interinactive'
  derp_evolution.png:
    name: 'Derp Evolution'
    credit: 'Interinactive'
    isImage: true
  driver_derp.jpg:
    name: 'Driver Derp'
    credit: 'Interinactive'
    isImage: true
  derpfall.gif:
    name: 'Derpfall'
    credit: 'Interinactive'
    isImage: true
  derpfan.gif:
    name: 'Derpfan'
    credit: 'Interinactive'
  derp_cloud.png:
    name: 'Derp Cloud'
    credit: 'Interinactive'
  derp_rate_0.png:
    name: 'Derp Rating'
    credit: 'Interinactive'
  derp_rate_1.png:
    name: 'Derp Rating'
    credit: 'Interinactive'
  derp_medal_of_honor.png:
    name: 'Medal of Honor Derp'
    credit: 'Interinactive'
  derp_medal_of_honor.png:
    name: 'Medal of Honor Derp'
    credit: 'Interinactive'
  360derp.jpg:
    name: '360 Derp'
    credit: 'Unknown'
    isImage: true
  depth_derp.png:
    name: 'Derp Depth Map'
    credit: 'Leo Natan'
    isImage: true
  derp_cevat_orly_rise.gif:
    name: 'Cevat Orly? Ryse Derp'
    credit: 'ixigia'
  derp_cloud_gaming.gif:
    name: "Google Stadia's Power of the Derp Cloud"
    credit: 'ixigia'
  derp_assassins_creed_valhalla.gif:
    name: "Assassin's Derp Valhalla"
    credit: 'ixigia'
  derp_assassins_creed_origins.gif:
    name: "Assassin's Derp Origins"
    credit: 'ixigia'
  derp_assassins_creed.gif:
    name: "Assassin's Derp"
    credit: 'ixigia'
  derp_pes.gif:
    name: 'Derp Evolution Soccer'
    credit: 'ixigia'
  derp_forza_horizon.gif:
    name: 'Forza Hurrizon 5 Derp'
    credit: 'ixigia'
  derp_thief_ixi.gif:
    name: 'Thi4f No Jump Derp'
    credit: 'ixigia'
  derp_rtx_on_off.gif:
    name: 'RTX On/Off Derp'
    credit: 'ixigia'
  derp_god_of_war.gif:
    name: 'God of Derp'
    credit: 'ixigia'
  derp_matrix4.gif:
    name: 'The Matrix Woahderps'
    credit: 'ixigia'
  derp_far_cry_primal.gif:
    name: 'Far Derp Primal'
    credit: 'ixigia'
  derp_watch_dogs_2.gif:
    name: 'Watch Derps 2 XP'
    credit: 'ixigia'
  derp_kojima_likes.gif:
    name: 'Kojima Japcrap Likes Derp'
    credit: 'ixigia'
  derp_tomb_raider.gif:
    name: 'Shadow of the Rambo Derp Raider'
    credit: 'ixigia'
  derp_fast_furious.gif:
    name: 'Derp and Hurrious: Mi Familia'
    credit: 'ixigia'
  derp_aspect_ratio.gif:
    name: 'The Evil Within Cinematic Black Bars'
    credit: 'ixigia'
    hideFromPicker: true
  derp_homefront.gif:
    name: 'Homefront Murica Derp Yeah'
    credit: 'ixigia'
  derp_vanquish.gif:
    name: 'Vanquish Derp'
    credit: 'ixigia'
  ChernoDerp.png:
    name: 'Chernoderp'
    credit: 'ixigia'
  derp_call_of_duty.gif:
    name: 'Cow a Doody Black Ops 3 Derp'
    credit: 'ixigia'
  derp_call_of_duty_ww2.gif:
    name: 'Cow a Doody WWII Derp'
    credit: 'ixigia'
  derp_battlefield.png:
    name: 'Battlederp'
    credit: 'ixigia'
  derp_baby_games.png:
    name: 'Derp Gaming'
    credit: 'ixigia'
  derp_aitd.gif:
    name: 'Alone in the Derp: Illumination'
    credit: 'ixigia'
    hideFromPicker: true
  derp_dexter.png:
    name: 'Derpxter'
    credit: 'ixigia'
  derp_rapthurr.gif:
    name: "Everybody's Gone to the Rapthurr"
    credit: 'ixigia'
  derp_star_citizen.gif:
    name: 'Robberyts Derp Indurrstries'
    credit: 'ixigia'
  derp_italy_eu.gif:
    name: 'Italy Contributions to EU'
    credit: 'ixigia'
  derp_mspaint.png:
    name: 'MSPaint.exe Derp'
    credit: 'ixigia'
  derp_grammar_nazi_feminazi.png:
    name: 'Grammar Feminazi Derp'
    credit: 'ixigia'
  derp_polygon.png:
    name: 'Polylol Derp'
    credit: 'ixigia'
  derp_dragon_age.png:
    name: 'Durrgon Age: Derpisition'
    credit: 'ixigia'
    isImage: true
  derp_nfs.png:
    name: 'Need for Speed: The Derp'
    credit: 'ixigia'
    isImage: true
  derp_take_two_rally.png:
    name: 'Durrt Rally Take 2 Edition'
    credit: 'ixigia'
    isImage: true
  derp_ghost_recon.png:
    name: "Tom Calancy's Derp Recon"
    credit: 'ixigia'
    isImage: true
  Molyderpeux.jpg:
    name: 'Molyderpeux'
    credit: 'ixigia'
    isImage: true
  derp_thi4f_cover.png:
    name: "Thi4f's Official Derp Cover"
    credit: 'ixigia'
    isImage: true
  derp_colonial_marines.jpg:
    name: 'Colon Marines Derp'
    credit: 'ixigia'
    isImage: true
  derp_effects.gif:
    name: 'Nextgen Effects Derp'
    credit: 'ixigia'
    isImage: true
  derp_moba_mspaint.png:
    name: 'MOBA MSPaint Derp'
    credit: 'ixigia'
    isImage: true
  derp_freitard.png:
    name: 'Freitard Derp'
    credit: 'ixigia'
  derp_f1.png:
    name: 'Formula Derp'
    credit: 'ixigia'
    isImage: true
  derp_rome_2.jpg:
    name: 'Rome II "1.0" Total Hurr Durr'
    credit: 'ixigia'
    isImage: true
  derp_syndicate.jpg:
    name: 'Syndicate 2012 Derp'
    credit: 'ixigia'
    isImage: true
  derp_usa_politics.gif:
    name: 'USA Derp Politics'
    credit: 'ixigia'
  linux.gif:
    name: 'Linux Derp'
    credit: '?'
    isImage: true